name: Python Packages Test

on:
  push:
    branches: [pre/v*]

jobs:
  build-wheels:
    name: build wheels using cibuildwheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: download dictionary for PGO
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm' }}
        run: bash fetch_dictionary.sh "20220519" "core"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Modify version for TestPyPI upload
        run: python ./python/modify_version_for_testpypi.py
      - name: cibuildwheel ${{ matrix.os }}
        uses: pypa/cibuildwheel@v3.0.0
        with:
          package-dir: python
          output-dir: python/dist
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            ./python/dist/*.whl
            ./python/dist/*.tar.gz

  build-sdist:
    name: build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python for sdist
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools setuptools-rust build
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Modify version for TestPyPI upload
        run: python ./python/modify_version_for_testpypi.py
      - name: build sdist
        working-directory: ./python
        run: bash build-sdist.sh

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: |
            ./python/dist/*.whl
            ./python/dist/*.tar.gz

  upload-to-testpypi: # run only if all have succeeded
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: dist/
          merge-multiple: true
      - name: List files to upload
        run: ls -R dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_TEST_USERNAME }}
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true

  install-and-test:
    needs: [upload-to-testpypi]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macOS-latest]
        target: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t"]
        include:
          - os: "ubuntu-latest"
            target: "sdist"
            python-version: "3.13"
          - os: "ubuntu-latest"
            target: "sdist"
            python-version: "3.14"
        exclude:
          - os: "windows-latest"
            target: "3.13t"
          - os: "windows-latest"
            target: "3.14t"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Quansight-Labs/setup-python@v5
        with:
          python-version: ${{ matrix.python-version || matrix.target }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Show compatible tags
        run: python -m pip debug --verbose
      - name: Install our module from TestPyPi
        if: ${{ matrix.target != 'sdist' }}
        run: python -m pip -vvvv install --pre -U -i https://test.pypi.org/simple/ SudachiPy
      - name: Install our module from TestPyPi (sdist)
        if: ${{ matrix.target == 'sdist' }}
        run: |
          python -m pip install -U setuptools setuptools-rust
          python -m pip -vvvv install --pre -U -i https://test.pypi.org/simple/ --no-build-isolation --no-binary SudachiPy SudachiPy
      - name: Install dependencies (dictionary)
        # this must be after sudachipy install
        run: python -m pip install sudachidict_core
      - name: Install dependencies (test pretokenizer)
        # tokenizers for py3.13t, py3.14, py3.14t are not provided yet
        if: ${{ matrix.target != '3.13t' && matrix.target != '3.14' && matrix.target != '3.14t' }}
        run: python -m pip install tokenizers

      - name: Run test
        if: ${{ matrix.target != '3.13t' && matrix.target != '3.14' && matrix.target != '3.14t' }}
        working-directory: ./python
        run: python -m unittest
      - name: Run test (skip pretokenizer test)
        # tokenizers for py3.13t, py3.14, py3.14t are not provided yet
        if: ${{ matrix.target == '3.13t' || matrix.target == '3.14' || matrix.target == '3.14t' }}
        working-directory: ./python
        run: ls tests/test_*.py | grep -v pretokenizer | xargs -I{} python -m unittest {}
      - name: Check that binary works (C mode)
        run: |
          sudachipy .github/data/input.txt -o result-c.txt
          git diff --color=always --no-index -- result-c.txt .github/data/expected-c.txt
      - name: Check that binary works (A mode)
        run: |
          sudachipy .github/data/input.txt -m A -o result-a.txt
          git diff --color=always --no-index -- result-a.txt .github/data/expected-a.txt
